clear all;close;clc;clc
% erriter= Lk+1 - Lk

rng('shuffle');


% initial value
m=5;
n=100;
beta=1;
t=1;
tau=1;
sigma=tau/1000;
epsilon=1e-5;
NumIter=5e4;

% random initial value
A=randn(m,n,'double');
AT=A';
b=randn(m,1);


% x,y,lambda initial value
tx=10*rand(n,1);
x=tx;
ty=10*rand(m,1);
y=ty; %ty: \tilde{y}
tlambda=10*rand(m,1);
lambda=tlambda; %tlambda: \tilde{\lambda}


% keep same initial value for other algorithm
xx=tx;
yy=ty;
llambda=tlambda;

% AADMM
% record change x,y,lambda
AH=[];
AV=[];
AVx=[];
AVy=[];
AVlambda=[];
AEX=[];
Aresidual=[];  % 记录残差 ||A*tx+ty-b||_2

tic
for i=1:NumIter
    
    % keep x,y,lambda
    X=x;
    Y=y;
    Lambda=lambda;
    
    % step1: update tx
    for j=1:1e3
        xf=x;
        P=beta/tau*AT*(A*xf+y-b-lambda/beta);
        x=max(xf-sigma*P-sigma,0)-max(-xf+sigma*P-sigma,0);
        ex=sqrt(sum((x-xf).*(x-xf)));
        if ex<1e-4
            break;
        end
    end
    tx=x;
    
    % record ex
    AEX(i)=ex;
    
    %step2: update tlambda
    Tlambda=tlambda; % keep tlambda
    tlambda=lambda-beta*(A*tx+y-b);
    
    %step3: update ty
    Ty=ty; %keep ty
    ty=tlambda;
    
    %step4: update t
    T=t; %keep t
    t=(1+sqrt(1+4*t^2))/2;
    
    %step5: update x
    x=tx;
    
    %step6: update y
    y=(t-1)/(2*t)*ty-(T-1)/(2*t)*Ty+T/(2*t)*((tlambda-lambda)+...
        (1-beta)*ty+beta*y);
    
    %step7: update lambda
    lambda=(t-1)/(2*t)*(2*tlambda-beta*ty)+...
        (T-1)/(2*t)*(beta*Ty-2*Tlambda)+...
        T/(2*t)*((beta-2)*lambda+(4-beta)*tlambda...
        +(beta^2-3*beta)*ty+(2*beta-beta^2)*Y);
    
    % record L value (i)
    AH(i)=log(i);
    Afvalue=abs(tau*sum(abs(tx))+1/2*sum(ty.*ty)-sum(tlambda.*(A*tx+ty-b))...
        -tau*sum(abs(X))-1/2*sum(Ty.*Ty)+sum(Tlambda.*(A*X+Ty-b)));
    AV(i)=log(Afvalue);
    
     % 记录残差 ||A*tx+ty-b||_2
    residual = norm(A*tx + ty - b, 2);
    Aresidual(i) = residual;
    
    % record error between update and solution
    erriter_x =sqrt(sum((x-X).*(x-X)));
    erriter_y=sqrt(sum((ty-Ty).*(ty-Ty)));
    erriter_lambda=sqrt(sum((tlambda-Tlambda).*(tlambda-Tlambda)));
    
    % record plot
    AVx(i)=(erriter_x);
    AVy(i)=(erriter_y);
    AVlambda(i)=(erriter_lambda);
    
    % 记录残差 ||A*tx+ty-b||_2
    residual = norm(A*tx + ty - b, 2);
    Aresidual(i) = residual;
    
    if Afvalue<epsilon
        break;
    end
    
end
toc
timet = toc

% record convergence point
APx=tx;
APy=ty;
APlambda=tlambda;

msg = sprintf(['The iteration of AADMM = %u. \n'], i);

% ADMM
% keep same initial value as AADMM
x=xx;
y=yy;
lambda=llambda;

% record change x,y,lambda
H=[];
V=[];
Vx=[];
Vy=[];
Vlambda=[];
EX=[];

tic
for i=1:NumIter
    
    % keep x,y,lambda
    X=x;
    Y=y;
    Lambda=lambda;
    
    % update x
    for j=1:1e3
        xf=x;
        P=beta/tau*AT*(A*xf+y-b-lambda/beta);
        x=max(xf-sigma*P-sigma,0)-max(-xf+sigma*P-sigma,0);
        ex=sqrt(sum((x-xf).*(x-xf)));
        if ex<1e-4
            break;
        end
    end
    
    % record ex
    EX(i)=ex;
    
    % update y
    y=(lambda-beta*(A*x-b))/(1+beta);
    % update lambda
    lambda=lambda-beta*(A*x+y-b);
    
    % record L value (i)
    H(i)=log(i);
    f1value=abs(tau*sum(abs(x))+1/2*sum(y.*y)...
        -tau*sum(abs(X))-1/2*sum(Y.*Y));
    f2value=sqrt(sum((A*x+y-b).*(A*x+y-b)));
    fvalue=max(f1value,f2value);
    V(i)=log(fvalue);
    
    % record error between update and solution
    erriter_x =sqrt(sum((x-X).*(x-X)));
    erriter_y=sqrt(sum((y-Y).*(y-Y)));
    erriter_lambda=sqrt(sum((lambda-Lambda).*(lambda-Lambda)));
    
    % record plot
    Vx(i)=(erriter_x);
    Vy(i)=(erriter_y);
    Vlambda(i)=(erriter_lambda);
    
    if fvalue<epsilon
        break;
    end
    
end
toc
timet = toc

% record iteration point (i+1)
Px=x;
Py=y;
Plambda=lambda;

Msg = sprintf(['The iteration of ADMM = %u. \n'], i);


% difference between AADMM and ADMM (point)
ADAAx=sqrt(sum((APx-Px).*(APx-Px)))/n;
ADAAy=sqrt(sum((APy-Py).*(APy-Py)))/m;
ADAAlambda=sqrt(sum((APlambda-Plambda).*(APlambda-Plambda)))/m;


% The difference of value of AADMM and ADMM
F=abs(tau*sum(abs(APx))+1/2*sum(APy.*APy)-sum(APlambda.*(A*APx+APy-b))...
      -(abs(tau*sum(abs(Px))+1/2*sum(Py.*Py))));

msg1 = sprintf(['The difference of the iterative points' ...
    'generated by ADMM and AADMM about x= %u. \n'], ADAAx);
msg2 = sprintf(['The difference of the iterative points' ...
    'generated by ADMM and AADMM about y= %u. \n'], ADAAy);
msg3 = sprintf(['The difference of the iterative points' ...
    'generated by ADMM and AADMM about lambda= %u. \n'], ADAAlambda);

msg6 = sprintf(['Afvalue= %u. \n'], Afvalue);
msg7 = sprintf(['fvalue= %u. \n'], fvalue);
msg10 = sprintf(['The difference of value of AADMM and ADMM= %u. \n'], F);

disp(msg1);
disp(msg2);
disp(msg3);
disp(msg6);
disp(msg7);
disp(msg);
disp(Msg);
disp(msg10);

figure
plot(H,V,'-b.');
hold on;
plot(AH,AV,'-r.'); %
xlabel('log(It.)','FontName','Times');
ylabel('log(Error)','FontName','Times');
% ylim([-12 5]);
yticks(-10:5:5);
legend('ADMM','AADMM')

figure
iterations_AADMM = 1:length(Aresidual);

% 处理零值：将 0 或小于 eps 的值替换为 1e-16
residual_plot = Aresidual;
residual_plot(residual_plot < 1e-15) = 1e-16;  % 将极小值/零替换为 1e-16

semilogy(iterations_AADMM, residual_plot, '-b.', 'LineWidth', 1.5);
xlabel('It.', 'FontName', 'Times');
ylabel('$\Vert A\tilde{x}^{k}+\tilde{y}^{k}-b\Vert$', 'FontName', 'Times', 'Interpreter', 'latex');
grid on;

% 可选：在图上标注收敛到零的位置
if any(Aresidual == 0)
    zero_idx = find(Aresidual == 0, 1, 'first');
    hold on;
    plot(zero_idx, 1e-16, 'ro', 'MarkerSize', 8, 'MarkerFaceColor', 'r');
    text(zero_idx, 1e-14, 'Converged to zero', 'FontName', 'Times', 'FontSize', 10);
    hold off;
end










